
add-file-nested: 
	../.build/x86_64-apple-macosx/debug/xcp --add-file Group2/bbbb.swift iOSTestProject.xcodeproj/project.pbxproj iOSTestProject --overwrite

add-group: 
	../.build/x86_64-apple-macosx/debug/xcp --add-group Group2 iOSTestProject.xcodeproj/project.pbxproj iOSTestProject --overwrite

