
reverse:
	git checkout -- iOSTestProject.xcodeproj

add-file: 
	../.build/x86_64-apple-macosx/debug/xcp --add-file Group2/bbbb.swift iOSTestProject.xcodeproj/project.pbxproj iOSTestProject 

add-group: 
	../.build/x86_64-apple-macosx/debug/xcp --add-group Group2 iOSTestProject.xcodeproj/project.pbxproj iOSTestProject 

remove-file:
	../.build/x86_64-apple-macosx/debug/xcp --remove-file iOSTestProject/AppDelegate.swift iOSTestProject.xcodeproj/project.pbxproj iOSTestProject 

remove-group:
	../.build/x86_64-apple-macosx/debug/xcp --remove-group iOSTestProject iOSTestProject.xcodeproj/project.pbxproj iOSTestProject 
